apiVersion: storage.k8s.io/v1beta1
kind: StorageClass  
metadata:
  name: heketi  
provisioner: kubernetes.io/glusterfs   
parameters:
  resturl: "http://172.16.100.50:8080"  
  restuser: "admin"  
  restuserkey: "key"
