apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-heketi
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /datastorage/heketi
    server: 10.0.0.15
