apiVersion: v1
kind: Route
metadata:
  name: heketi
spec:
  host: heketi-heketi.apps.nithralas.local
  port:
    targetPort: http
  to:
    kind: Service
    name: heketi
    weight: 100
  wildcardPolicy: None
