apiVersion: v1
kind: Service
metadata:
  name: heketi      
spec:
  selector: 
    name: "heketi" 
  ports:
  - name: "http"
    port: 8080              
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
